### ISSUE TITLE
Update Spec with CrossGroupObjectReference for target

### ISSUE THREAD

**Issue by ericuldall** [West-Coast-Devops/scheduled-scaler#2]
Per @DirectXMan12  in https://github.com/kubernetes/kubernetes/issues/49931#issuecomment-370536165

Update Spec to use CrossGroupObjectReference so it is consistent with the current HPA Spec.

*hpa target:*
```
target:
  kind: HorizontalPodAutoscaler
  apiVersion: autoscaling/v1
  name: foobar
```
*instance group target:*
```
target:
  kind: InstanceGroup
  apiVersion: compute/v1
  name: foobar
```
